### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by utzuro** [masakichi/tango#2]
I've used 'go get github.com/masakichi/tango' successfully but that wasn't enough to run 'tango' command. Should there be any additional steps?
I have /home/username/go/src/github.com/masakichi/tango folder.
I'm new to go, so maybe I'm missing something obvious.
Archlinux. Go version: go1.13.4 linux/amd64
Thank you in advance.

**Comment by yuanji-dev** [comment]
hello @utzuro9 

you can run `/home/username/go/bin/tango` to test if it works, or try to add `$GOPATH/bin`  to your `$PATH` so you can run `tango` directly.

**Comment by utzuro** [comment]
It worked! Thank you @masakichi
